name: Java CI Build & Test

on:
  push:
    branches: [ "main", "feature/**", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar JDK 17 y caché de Maven
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compilar y ejecutar pruebas
        run: mvn -B clean verify
